### ISSUE TITLE
epic: intel hardware inferencing for nitro

### ISSUE THREAD

**Issue by tikikun** [janhq/nitro#140] opened 2023-11-15 06:53 UTC
Using the below package from intel 

https://github.com/intel/intel-extension-for-transformers

![image](https://github.com/janhq/nitro/assets/22268502/f20abd3d-229a-4b8b-88ef-be4dab6d8637)

They claimed to outperform llama.cpp with their custom implementation. A potential candidate for integration.

**Comment by 0xSage** [comment] 2023-11-28 03:04
dupe of #214

**Closed by 0xSage** 2023-11-28 03:04 UTC
Labels: type: epic, type: feature request
