### ISSUE TITLE
feat: Apply queue system for embedding

### ISSUE THREAD

**Issue by louis-jan** [janhq/nitro#403] opened 2024-02-01 05:34 UTC
**Problem**
When using nitro for embedding use case, it can get stuck without proper response due to queue system is not implemented. Please help on this.

**Success Criteria**
I can send many requests at the same time, get return responses serially.

**Additional context**

**Comment by tikikun** [comment] 2024-02-02 09:38
duplicate of https://github.com/janhq/nitro/issues/404

**Closed by tikikun** 2024-02-02 09:38 UTC
Labels: type: feature request
