### ISSUE TITLE
feat: Nitro should support docker image

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/nitro#62] opened 2023-10-07 02:53 UTC
**Problem**
- Manual steps in README.md to build make me frustrated, esp. when there are system deps. bugs

**Success Criteria**
- Dockerfile - related to #32 
- Prebuilt docker images

**Additional context**
None

**Comment by 0xSage** [comment] 2023-10-10 02:09
Closing as dupe of #32

**Closed by 0xSage** 2023-10-10 02:09 UTC
Labels: type: feature request
